Kostya devel
urock/network_operator pull request #3
Opened 2022-10-22 14:00 UTC by KostyaYamshanov

Добавил простое приложение для тестов сетевого оператора. 

Добавил небольшой модуль для тестов

Добавил reader как поле в NOP, чтобы при необходимости можно было прочитать матрицу сразу с помощью сетевого оператора.

Добавил тесты на чтение матрицы и файла с параметрами

2022-10-23 07:10 UTC, urock requested changes

2022-10-23 07:10 UTC, urock commented on app/simple_app.cpp
> +        ("start_x,x", po::value(&start_x), "start x")
добавить еще макс время работы программы, останавливать симуляция по достижению этого времени. 

по умолчанию путь будет 10 сек

2022-10-23 07:10 UTC, urock commented on app/simple_app.cpp
> +#include "nop.hpp"
переименовать simple_app в run_to_goal

2022-10-24 10:52 UTC, KostyaYamshanov commented on app/simple_app.cpp
> +#include "nop.hpp"
переименовал, готово

2022-10-24 10:52 UTC, KostyaYamshanov commented on app/simple_app.cpp
> +        ("start_x,x", po::value(&start_x), "start x")
Добавил

2022-10-24 10:53 UTC, KostyaYamshanov commented
```
./run_to_goal -x 1 -y 1 -s false -t 15

START 
Initial state = 1 1 0
Goal state = 0 0 0
State -0.00726376 -0.00515791 -0.00443403
spend time: 15.01 (s)
END
```

2022-11-04 10:27 UTC, urock approved these changes

2022-11-04 11:05 UTC, merged